# Generated by Django 4.2.5 on 2023-09-24 13:27

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(verbose_name='Posts text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(verbose_name='Posts title'),
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comment')),
                ('status', models.CharField(max_length=20, validators=[posts.models.status_validator], verbose_name='status')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_dt', models.DateTimeField(blank=True, null=True, verbose_name='updated')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='posts.post', verbose_name='Post ID')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'db_table': 'posts_comments',
            },
        ),
    ]
