# Generated by Django 4.2.5 on 2023-09-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_options_alter_post_body_alter_post_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='status',
            field=models.CharField(choices=[('open', 'opened'), ('close', 'closed'), ('in progress', 'in progressed')], max_length=20, verbose_name='status'),
        ),
    ]
