# Generated by Django 4.2.5 on 2023-09-25 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_postcomment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='post created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='updated_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='post updated'),
        ),
    ]
