# Generated by Django 4.2.5 on 2023-09-27 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_postcomment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='posts_comment', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.CreateModel(
            name='Csv_Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField(verbose_name='UUID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='csv created')),
                ('updated_dt', models.DateTimeField(blank=True, null=True, verbose_name='csv updated')),
                ('company_name', models.TextField(verbose_name='company')),
                ('report_d', models.DateField(auto_now_add=True, verbose_name='report day')),
                ('att_001', models.FloatField(blank=True, null=True, verbose_name='credit')),
                ('att_002', models.FloatField(blank=True, null=True, verbose_name='deposit')),
                ('att_003', models.FloatField(blank=True, null=True, verbose_name='fine')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_attributes', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'csv_attribute',
                'verbose_name_plural': 'csv_attributes',
                'db_table': 'csv_attributes',
            },
        ),
        migrations.CreateModel(
            name='Counted_Att_Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.IntegerField(verbose_name='UUID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='csv created')),
                ('updated_dt', models.DateTimeField(blank=True, null=True, verbose_name='csv updated')),
                ('is_active', models.BooleanField(blank=True, null=True, verbose_name='is active')),
                ('att_formula', models.TextField(verbose_name='formula')),
                ('att_formula_sql', models.TextField(blank=True, null=True, verbose_name='SQL formula')),
                ('description', models.TextField(verbose_name='description')),
                ('nested_level', models.IntegerField(blank=True, null=True, verbose_name='nested level')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counted_att_formula', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'counted_att_formula',
                'verbose_name_plural': 'counted_att_formulas',
                'db_table': 'counted_att_formula',
            },
        ),
        migrations.CreateModel(
            name='Counted_Att',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField(verbose_name='UUID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='csv created')),
                ('updated_dt', models.DateTimeField(blank=True, null=True, verbose_name='csv updated')),
                ('is_active', models.BooleanField(blank=True, null=True, verbose_name='is active')),
                ('name_cntd_att', models.TextField(verbose_name='attribute name')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counted_att', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'counted_att',
                'verbose_name_plural': 'counted_atts',
                'db_table': 'counted_att',
            },
        ),
    ]
