# Generated by Django 4.2.5 on 2023-09-27 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_owner_alter_postcomment_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counted_att_formula',
            name='uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='posts.counted_att', verbose_name='UUID'),
        ),
    ]
