# Generated by Django 4.2.5 on 2023-09-27 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_counted_att_formula_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='owner',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='owner',
            new_name='author',
        ),
    ]
