# Generated by Django 4.2.5 on 2023-09-28 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0010_rename_owner_post_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counted_att',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counted_atts', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='counted_att',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='counted_att',
            name='updated_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='counted_att',
            name='uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='posts.csv_attribute', verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='counted_att_formula',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counted_att_formulas', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='counted_att_formula',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='counted_att_formula',
            name='updated_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='csv_attribute',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='csv_attribute',
            name='updated_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='updated'),
        ),
    ]
