# Generated by Django 4.2.5 on 2023-09-28 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_counted_att_formula_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='counted_att_formula',
            name='cntd_att_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to='posts.counted_att', verbose_name='Counted att id'),
            preserve_default=False,
        ),
    ]
