# Generated by Django 4.2.5 on 2023-09-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='pdf',
            new_name='filename',
        ),
    ]
