# Generated by Django 4.2.5 on 2023-10-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincatalogfields',
            name='origin',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='countedattrformula',
            name='sql_query',
            field=models.TextField(blank=True, null=True),
        ),
    ]
