# Generated by Django 4.2.5 on 2023-10-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_maincatalogfields_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringmodel',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
