# Generated by Django 4.2.5 on 2023-10-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_innres_result_score_alter_innres_scoring_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innres',
            name='scoring_model',
            field=models.ManyToManyField(blank=True, to='backend.scoringmodel'),
        ),
    ]
