# Generated by Django 4.2.5 on 2023-10-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_csvattributes_address_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvattributes',
            name='recovery_initiation',
            field=models.FloatField(default=False, null=True),
        ),
    ]
