# Generated by Django 4.2.5 on 2023-09-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_pdf_files_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='filename',
            field=models.FileField(upload_to=''),
        ),
    ]
