# Generated by Django 4.2.5 on 2023-10-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_innres_scoring_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innres',
            name='author_id',
            field=models.CharField(blank=True, max_length=125),
        ),
    ]
