# Generated by Django 4.2.5 on 2023-10-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_countedattributes_scoring_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringmodel',
            name='version',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='scoringmodelhistory',
            name='version',
            field=models.IntegerField(blank=True),
        ),
    ]
