# Generated by Django 4.2.5 on 2023-09-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_countedattributes_csvattributes_fileattributes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countedattributes',
            options={'verbose_name': 'counted_attributes'},
        ),
        migrations.AddIndex(
            model_name='countedattributes',
            index=models.Index(fields=['name_counted_attr', 'created_date'], name='counted_att_name_co_405d20_idx'),
        ),
        migrations.AlterModelTable(
            name='countedattributes',
            table='counted_attributes',
        ),
    ]
