# Generated by Django 4.2.5 on 2023-09-28 18:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_countedattributes_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnRes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('author_id', models.CharField(max_length=125)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('inn', models.IntegerField()),
                ('result_score', models.IntegerField()),
                ('scoring_model', models.ManyToManyField(to='backend.scoringmodel')),
            ],
            options={
                'verbose_name': 'inn_res',
                'db_table': 'inn_res',
                'indexes': [models.Index(fields=['inn', 'created_date'], name='inn_res_inn_5769c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='CountedAttrFormula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('author_id', models.CharField(max_length=125)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('attr_formulas', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('sql_query', models.TextField()),
                ('nested_level', models.IntegerField()),
                ('cntd_attr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.countedattributes')),
            ],
            options={
                'verbose_name': 'counted_attr_formula',
                'db_table': 'counted_attr_formula',
                'indexes': [models.Index(fields=['attr_formulas', 'created_date'], name='counted_att_attr_fo_63c9d8_idx')],
            },
        ),
    ]
