# Generated by Django 4.2.5 on 2023-10-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_scoringmodel_author_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countedattributes',
            name='author_id',
            field=models.CharField(blank=True, max_length=125),
        ),
    ]
