# Generated by Django 4.2.5 on 2023-10-10 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0007_alter_countedattributes_author_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringmodel',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='scoringmodelhistory',
            name='author_id',
        ),
        migrations.AddField(
            model_name='scoringmodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoringmodel_create', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='scoringmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoringmodel_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
    ]
