# Generated by Django 4.2.5 on 2023-10-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_scoringmodel_author_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoringmodel',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='scoringmodelhistory',
            old_name='author_id',
            new_name='author',
        ),
    ]
