# Generated by Django 4.2.5 on 2023-10-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_author_id_scoringmodel_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringmodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='scoringmodelhistory',
            name='author',
        ),
        migrations.AddField(
            model_name='scoringmodel',
            name='author_id',
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AddField(
            model_name='scoringmodelhistory',
            name='author_id',
            field=models.CharField(blank=True, max_length=125),
        ),
    ]
