# Generated by Django 4.2.5 on 2023-10-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_remove_countedattributes_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvattributes',
            name='recovery_initiation',
            field=models.FloatField(default=False, null=True),
        ),
    ]
