export const users = [
  // {
  //   id: 1,
  //   solvencyRisk: "Платежеспособность",
  //   sources: "Источник информации",
  //   managers: "Менеджер",
  //   status: "Кредитор",
  //   type: "Тип долга",
  //   category: "Категория",
  //   positive: "Положительное решение",
  //   stage: "Стадия рассмотрения",
  //   negative: "Отрицательное решение",
  //   support: "Мера поддержки запрашиваемая клиентом",
  //   PRD: "Представительсво ПРД",
  //   regions: 'Регион',
  //   name: "Наименование клиента",
  //   INN: "ИНН",
  //   dateAppealsToMIDUOL: "Дата обращения в МИДУОЛ",
  //   dateEventOccurance: "Дата наступления события",
  //   deptSum: "Сумма задолженности",
  //   descr: "Описание события",
  //   activity: "Вид деятельности",
  //   sourceNumber: "Источник информации. Номер",
  //   representativeNameEndTitle: "Представитель клиента. ФИО, должность",
  //   representativeNumber: "Представитель клиента. Телефон",
  //   representativeMail: "Представитель клиента. Почта",
  //   notes: "Примечания",
  //   termMesureNecessary: "Срок, на который необходимо предоставить меры",
  //   firstMeetDate: "Дата первой встречи",
  //   termMesure: "На сколько предоставлена мера (в месяцах)",
  //   petitionAuthor: "От кого ходатайство (для МС)",
  //   settledDebtAmount: "Сумма урегулированной задолжности (тыс руб)",
  //   amountReceivedIntoBudget: "Сумма, поступившая в бюджет (тыс руб)",
  //   nearestDateForFulfillment: "Близжайший срок исполнения обязательства (до какого момента отложены меры)",
  //   notInForce: "Не вступило в силу рассрочка/отсрочка (тыс руб)",
  //   caseNumber: "Номер дела",
  //   courtMCApprovalDate: "Дата утверждения МС судом",
  //   amountOfClaimsMC: "Сумма требований, вошедших в МС",
  //   MCexpirationDate: "Дата окончания МС",
  //   amountOfFulfilledObligations: "Сумма исполненных обязательств (тыс руб)",
  //   sum: "Сумма (тыс руб)",
  //   amountOfTechnicalOverdueDebt: "Сумма технической просроченной задолженности (тыс руб)",
  //   pledgeOfProperty: "Залог имущества (тыс руб)",
  //   surety: "Поручительство (тыс руб)",
  //   bankGuarantee: "Банковская гарантия (тыс руб)",
  //   deptorDirectionDate: "Дата направления ДОЛЖНИКУ уведомления (претензии)",
  //   garantorDirectionDate: "Дата направления ПОРУЧИТЕЛЮ уведомления (претензии)",
  //   pledgetorDirectionDate: "Дата направления ЗАЛОГОДАТЕЛЮ уведомления (претензии)",
  //   checkPoint: "25.05.23",
  //   activityRisk: "Деловая активность (риск)",
  //   withdrawalOfAssetsRisk: "Вывод активов (риск)",
  // },
  {
    id: 1,
    solvencyRisk: "Высокий риск",
    sources: "",
    managers: "Панфилова И. О,",
    status: "Кредитор",
    type: "",
    category: "",
    positive: "Мировое соглашение",
    stage: "Работа завершена",
    negative: "-",
    support: "Мировое соглашение",
    PRD: "МИДУОЛ",
    regions: "77 г. Москва",
    name: "ООО 'Розочка'",
    INN: "345352342",
    dateAppealsToMIDUOL: "",
    dateEventOccurance: "",
    deptSum: "",
    descr: "",
    activity: "",
    sourceNumber: "",
    representativeNameEndTitle: "",
    representativeNumber: "",
    representativeMail: "",
    notes: "",
    termMesureNecessary: "",
    firstMeetDate: "",
    termMesure: "",
    petitionAuthor: "",
    settledDebtAmount: "",
    amountReceivedIntoBudget: "",
    nearestDateForFulfillment: "",
    notInForce: "",
    caseNumber: "",
    courtMCApprovalDate: "",
    amountOfClaimsMC: "",
    MCexpirationDate: "",
    amountOfFulfilledObligations: "",
    sum: "",
    amountOfTechnicalOverdueDebt: "",
    pledgeOfProperty: "",
    surety: "",
    bankGuarantee: "",
    deptorDirectionDate: "",
    garantorDirectionDate: "",
    pledgetorDirectionDate: "",
    checkPoint: "25.05.23",
    activityRisk: "Средний риск",
    withdrawalOfAssetsRisk: "Средний риск",
  },
]
